# Generated by Django 6.1 on 2026-09-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_superadmin',
            field=models.BooleanField(default=False, help_text='Designates access to the /master-admin/ super-admin portal.'),
        ),
    ]
