# Generated by Django 6.1 on 2026-08-24 19:55

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional one-time admission fee collected at registration. Tracked separately from monthly tuition and reported on the dashboard.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
