# Generated by Django 6.1 on 2026-08-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_admission_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='roll_number',
            field=models.CharField(blank=True, help_text='Roll number unique within the class (optional)', max_length=50, verbose_name='Roll Number'),
        ),
    ]
