# Generated by Django 6.1 on 2026-09-06 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_seed_classes'),
        ('students', '0004_student_roll_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('NEW_ADMISSION', 'New Admission'), ('REGULAR', 'Regular'), ('PROMOTED', 'Promoted')], default='NEW_ADMISSION', help_text='Visual tag to distinguish student progression.', max_length=20),
        ),
        migrations.CreateModel(
            name='StudentAcademicHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_year', models.CharField(help_text='e.g. 2025-2026', max_length=20)),
                ('fee_clearance_status', models.CharField(help_text="e.g. '12/12 Paid'", max_length=50)),
                ('status_tag', models.CharField(choices=[('NEW_ADMISSION', 'New Admission'), ('REGULAR', 'Regular'), ('PROMOTED', 'Promoted')], max_length=20)),
                ('promoted_date', models.DateField(auto_now_add=True)),
                ('school_class', models.ForeignKey(blank=True, help_text='The class the student completed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_students', to='classrooms.schoolclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_history', to='students.student')),
            ],
            options={
                'verbose_name': 'Academic History',
                'verbose_name_plural': 'Academic Histories',
                'ordering': ['-promoted_date'],
            },
        ),
    ]
