# Generated by Django 6.1 on 2026-08-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='School Management System', help_text='Shown in the sidebar, page titles, login screen and all printable documents.', max_length=120)),
                ('school_phone', models.CharField(blank=True, default='', help_text='Contact number printed on receipts, payslips and report letterheads.', max_length=20)),
                ('school_logo', models.ImageField(blank=True, help_text='Logo shown next to the school name on printed documents.', null=True, upload_to='school_logo/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School Settings',
                'verbose_name_plural': 'School Settings',
            },
        ),
    ]
