# Generated by Django 6.1 on 2026-09-16 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notification_title'),
        ('students', '0005_student_status_studentacademichistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(editable=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_messages', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Message',
                'verbose_name_plural': 'Student Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
