# Generated by Django 6.1 on 2026-09-17 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_studentmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmessage',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentmessage',
            name='reply',
            field=models.TextField(blank=True, help_text='Reply from the school administration.', null=True),
        ),
    ]
