# Generated by Django 6.1 on 2026-09-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="URL-safe identifier (e.g. 'al-huda-academy'). Used in /t/<slug>/…", max_length=60, unique=True)),
                ('school_name', models.CharField(help_text='Display name shown in the master dashboard.', max_length=150)),
                ('db_name', models.CharField(editable=False, help_text='Auto-generated database filename/alias for this tenant.', max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Kill Switch — when False, all requests for this tenant return a Suspended page.')),
                ('admin_email', models.EmailField(blank=True, default='', max_length=254)),
                ('admin_phone', models.CharField(blank=True, default='', max_length=20)),
                ('max_students', models.PositiveIntegerField(default=500, help_text='Optional student quota for this school.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tenant School',
                'verbose_name_plural': 'Tenant Schools',
                'ordering': ['school_name'],
            },
        ),
    ]
