# Generated by Django 6.1 on 2026-09-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Lock school portal — when True, users are blocked and see a custom message.'),
        ),
    ]
