# Generated by Django 6.1 on 2026-09-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='error_log',
            field=models.TextField(blank=True, default='', editable=False, help_text='Last auto-migration failure traceback (plain text).'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='migration_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROVISIONING', 'Provisioning'), ('OK', 'OK'), ('FAILED', 'Failed')], default='PENDING', editable=False, help_text='Auto-migration status of the tenant database. PROVISIONING = migration in progress; OK = schema up to date; FAILED = the last auto-migration raised an unhandled error.', max_length=20),
        ),
    ]
