# Generated by Django 6.1 on 2026-08-18 17:00

import django
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models

# Django 6.1 renamed CheckConstraint's `check` kwarg to `condition`.
_CHECK_KWARG = "condition" if django.VERSION >= (6, 1) else "check"


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], verbose_name='Fee Month')),
                ('fee_year', models.PositiveSmallIntegerField(verbose_name='Fee Year')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_date', models.DateField()),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending')], default='PAID', max_length=10)),
                ('reference', models.CharField(blank=True, help_text='Receipt/payment reference number if required', max_length=50)),
                ('is_extra', models.BooleanField(default=False, help_text='Explicitly-allowed extra/second payment for the same month')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_fees', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fees', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Fee',
                'verbose_name_plural': 'Student Fees',
                'ordering': ['-fee_year', '-fee_month', '-payment_date'],
                'indexes': [models.Index(fields=['student', 'fee_year'], name='fees_studen_student_f327a0_idx'), models.Index(fields=['fee_month', 'fee_year'], name='fees_studen_fee_mon_d260c6_idx'), models.Index(fields=['payment_date'], name='fees_studen_payment_700a8d_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_extra', False)), fields=('student', 'fee_month', 'fee_year'), name='unique_student_fee_month'), models.CheckConstraint(**{_CHECK_KWARG: models.Q(('amount__gt', 0))}, name='fee_amount_positive')],
            },
        ),
    ]
