# Generated by Django 6.1 on 2026-09-06 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_seed_classes'),
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfee',
            name='school_class',
            field=models.ForeignKey(blank=True, help_text='The class the student was in when this fee was paid.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fees_collected', to='classrooms.schoolclass'),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='session_year',
            field=models.CharField(blank=True, help_text="Academic session, e.g., '2025-2026'", max_length=9),
        ),
    ]
