# Generated by Django 6.1 on 2026-08-18 17:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classrooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('cnic', models.CharField(blank=True, max_length=20, verbose_name='CNIC (optional)')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('address', models.TextField(blank=True)),
                ('cnic_front_pic', models.ImageField(blank=True, null=True, upload_to='teachers/cnic/', verbose_name='CNIC Front Picture (optional)')),
                ('cnic_back_pic', models.ImageField(blank=True, null=True, upload_to='teachers/cnic/', verbose_name='CNIC Back Picture (optional)')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='teachers/photos/', verbose_name='Teacher Picture (optional)')),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monthly Salary')),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_classes', models.ManyToManyField(blank=True, related_name='assigned_teachers', to='classrooms.schoolclass')),
                ('user', models.OneToOneField(blank=True, help_text='Linked login account (created in ID Management)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ['teacher_id'],
            },
        ),
        migrations.CreateModel(
            name='TeacherSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], verbose_name='Salary Month')),
                ('salary_year', models.PositiveSmallIntegerField(verbose_name='Salary Year')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_date', models.DateField()),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending')], default='PAID', max_length=10)),
                ('reference', models.CharField(blank=True, help_text='Payment reference if required', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_salaries', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salaries', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Teacher Salary',
                'verbose_name_plural': 'Teacher Salaries',
                'ordering': ['-salary_year', '-salary_month', '-payment_date'],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'salary_month', 'salary_year'), name='unique_teacher_salary_month'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='salary_amount_positive')],
            },
        ),
    ]
