# Generated by Django 6.1 on 2026-08-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft-delete flag: inactive teachers are hidden from lists but their salary/attendance history is preserved for financial reports.'),
        ),
    ]
