# Generated by Django 6.1 on 2026-08-23 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_seed_classes'),
        ('teachers', '0002_teacher_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='assigned_class',
            field=models.ForeignKey(blank=True, help_text='Primary class assigned to this teacher', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class_teachers', to='classrooms.schoolclass', verbose_name='Assigned Class'),
        ),
    ]
