# Generated by Django 6.1 on 2026-08-25 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teacher_assigned_class'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent')], default='PRESENT', max_length=10)),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('QR', 'QR Scan'), ('MANUAL', 'Manual')], default='QR', help_text='How this attendance entry was recorded', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_teacher_attendance', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qr_attendance_records', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Teacher Attendance',
                'verbose_name_plural': 'Teacher Attendance Records',
                'ordering': ['-date', 'teacher__teacher_id'],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'date'), name='unique_teacher_attendance_date')],
            },
        ),
    ]
