# Generated by Django 6.1 on 2026-08-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_teacherattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherattendance',
            name='source',
            field=models.CharField(choices=[('QR', 'QR Scan'), ('MANUAL', 'Manual Entry'), ('AUTO', 'Auto-System')], default='QR', help_text='How this attendance entry was recorded', max_length=10),
        ),
        migrations.AlterField(
            model_name='teacherattendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LEAVE', 'Leave')], default='PRESENT', max_length=10),
        ),
    ]
